### ISSUE TITLE
As WRES team, I would like to identify a candidate for github Release v6.25, test it, and if it passes, deploy it; candidate RC1: 68ecbc0364c927a98a48e3931359d7dccdc55819932c8c7aebd25620b947b387 wres-20240821-1d5b305.zip

### ISSUE THREAD

**Issue by ArvinEsmailzadeh** [NOAA-OWP/wres#271]
- [x] 1 - Update vulnerable (or more) libraries in WRES applications (use gradle task and/or inspect build.gradle vs repositories)
- [x] 2 - Tag a commit as staging to kick off pre-release workflow (Pre-release github action)
- [x] 3 - Nominate a commit that has passed the pre-release workflow (Pre-release github action)
- [x] 4 - Check nominated version passes live external services tests (Results sent via emails)
- [x] 5 - Check nominated version passes full system tests (Results sent via emails)
- [x] 6 - Test candidate with 900 series system tests (WRES Test VM or PC)
- [x] 7 - Test migration from scratch (new database instance) - migration succeeds with no issues
- [x] 8 - Test candidate by doing database migration from previous release db with half of system test data to this release with no issues
- [x] 9 - Test candidate with identified alpha (internal) User Acceptance Tests (-ti)
- [x] 10 - Push yml files changed
- [x] 11 - Tag the commits that produced the release that passed everything and was already deployed to -prod
- [x] 12 - Close tickets actually completed in this release and move tickets not completed to backlog
- [x] 13 - Update the ITSG deployment documentation with image ids
- [x] 14 - Update database documentation in wiki
- [x] 15 - Update user documentation

All:

This task is to track the identification of a release candidate for Release 6.22 through its deployment to our production area (currently -prod COWRES). Once we identify a candidate, update the Subject to identify the version number, check off the appropriate boxes if the candidate passes them, and push it forward through the next stages. If a candidate fails any stage, fix the issue, and start over. When a candidate passes all stages, then we will deploy/release it.

Please feel free to modify the checklist to better reflect reality.

Tasks completed as availability allows.

Updating the database schemas, diagrams if needed, data dictionary (if ready), etc. provided [here](https://vlab.noaa.gov/redmine/projects/wres/wiki/WRES_Pairing_Database_Schema_and_Related_Diagrams).

For user acceptance testing, scan all tickets on-hold or resolved to see if UAT is mentioned at the bottom.

Links to O&M documentation:

WRES Application for Deployment (update with each deployment): https://docs.google.com/document/d/1Ev2a1P_suaC3HNt4dKuqEkw6C-VmmCmI9PFcq7dH6aQ
COWRES O&M Document:https://docs.google.com/document/d/1XqQjyYREp9ruXSpUG4ey6x5DjaETAXnSEUOlz1JJypE
Deployment instructions: https://vlab.noaa.gov/redmine/projects/wres/wiki/COWRES_Deployment_Process_Instructions_(Github)

**Comment by james-d-brown** [comment]
As noted in the dependency ticket, you need to remove the api key from the `build.gradle`...

**Comment by james-d-brown** [comment]
Arvin, you need to get input from Evan on the steps in this ticket. Many of them do *not* apply to a github release.

We will need a separate ticket with the steps for a cowres deployment on vlab.

Two tickets, two separate lists. Again, ask Evan to help you split out the tasks. Some gates (e.g., 25) will even need to be split into parts because the wikis are here now.

**Comment by epag** [comment]
Steps 7 and 8 from that list are currently covered in the pre-release github action so they are no longer needed:

https://github.com/NOAA-OWP/wres/actions/runs/10496405279/job/29077175581

It will be a bit of a pain to juggle between the two tickets but I think the correct split between vlab and github would be the following:
Github:
- 1 - 8 
- 13
- 18 - 19
- 22 - 25

VLab:
- 9 - 12
- 14 - 17
- 20 - 21
- 26-30

**Comment by epag** [comment]
We should be able to revisit this process once the ticket to automate the staging deployment gets underway

**Comment by james-d-brown** [comment]
I think 23 is vlab (it mentions ITSG, which is about NWCAL) and 27 will need to be github, but I'm not sure we've migrated that wiki page yet.

**Comment by ArvinEsmailzadeh-NOAA** [comment]
[900x_log.txt](https://github.com/user-attachments/files/16711227/900x_log.txt)

900x series tests completed.

Arvin

**Comment by HankHerr-NOAA** [comment]
Arvin:

When the VLab ticket paired with this one is created, and check lists updated, please add the following 6.25-specific check list item 
to the VLab ticket so that we don't forget to do it:

Put the new entry User Support wiki in place and remove the deprecated wikis.  

Thanks,
Hank

**Comment by HankHerr-NOAA** [comment]
Noting here, per discussion with Arvin, testing task #62 is to be handled during the UAT portion of this deployment using the staging COWRES. It should therefore be expected that UAT will take a day or two, at least, not just hours, and that that testing might lead to additional release candidates if issues are found (but that often occurs regardless). 

I may be just stating the obvious,

Hank

**Comment by HankHerr-NOAA** [comment]
James:

I updated the metrics list wiki:

https://github.com/NOAA-OWP/wres/wiki/List-of-Metrics-Available

That wiki appeared to miss some metrics, so I made some updates, and then added the difference metrics.  The upper table, where the metrics are explicitly listed as they are specified in YAML, is ugly due to the column widths being insufficient. Is there a better way to display it?

The lower table was the most out of date with metrics missing altogether, such as Sum Square Error and Median Error among others. I attempted to add the missing metrics and then used an asterisk to mark those with a "difference" version. 

I encourage you to review the wiki thoroughly and let me know what is missing and if you have any better ideas for how to display the upper table. Both tables are in HTML, so, if you'd rather I figure out how to edit the tables, I'm willing. I did manage to add rows to the bottom table, which was tricky because of some cells spanning multiple rows.  

Thanks,

Hank

**Comment by james-d-brown** [comment]
Starring works well.

I am now wondering if we need the first table at all. It is uglier than the second table and, well, does it really add anything?

I note the numbering is off in the bottom table, but I can fix that.

Also, yes, there are some metrics missing from the bottom table, like the box plots for single-valued data.

Delete the top table?

**Comment by HankHerr-NOAA** [comment]
If you are in there, please do remove the top table. Its just too ugly.

The one thing the top table did that the bottom table didn't was provide the specific YAML metric names in all lower case so they could copy-and-paste. I guess we can point them to the schema for that or let them know that, in YAML, it needs to be all lower case.

Or is that a requirement? If someone specifies capitalized metrics, will WRES accept it?

Hank

**Comment by james-d-brown** [comment]
Done, I think that is a lot cleaner. Please confirm. I removed the ToC too because, well, no longer needed.

Yes, names are case sensitive - I clarified that in the intro.

**Comment by HankHerr-NOAA** [comment]
Much better. Thanks!

Hank

**Comment by HankHerr-NOAA** [comment]
All checkboxes are checked. Have we completed all steps for this ticket?

Hank

**Comment by ArvinEsmailzadeh** [comment]
This ticket is done for the deployment.

Arvin
