### ISSUE TITLE
As a developer, I want all logging appenders to show the same basic information (process, thread etc.)

### ISSUE THREAD

**Issue by epag** [NOAA-OWP/wres#290]
---

Author Name: **James** (James)
Original Redmine Issue: 99892, https://vlab.noaa.gov/redmine/issues/99892
Original Date: 2021-12-20

---

Given N logging appenders
When I inspect the logging from each appender
Then I expect the same basic information in each

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2021-12-20T22:54:30Z

---

In other words, I want to discuss these two notes in the @logback.xml@

```
    <!-- Some prefer timestamps, thread name, level, class name, etc. -->
.
.
.
    <!-- some prefer the message to be printed as formatted in the code -->

```

It is extremely annoying that the logging I see in my ide (standard out) does not contain the thread information, in particular, but I would like logging to be par in all contexts.

**Comment by james-d-brown** [comment]
Rendering logging equal in all contexts is not hard, but there is a separate issue about the pid not appearing in all contexts, notably in any thread created by a thread pool, where the MDC context is lost. Needs a separate ticket, though.
