### ISSUE TITLE
Spin up postgres database to test database integrity/migrations as part of our release process 

### ISSUE THREAD

**Issue by epag** [NOAA-OWP/wres#30]
Spin up a postgres database instance as part of the pre-release or release workflows to automate the testing of database migrations 

https://github.com/liquibase-github-actions/update
https://docs.liquibase.com/commands/home.html
https://github.com/liquibase/liquibase-github-action-example
https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers

Related work:
- [x] #32

**Comment by epag** [comment]
Okay, thinking through of what EXACTLY we are testing with our current database migration steps in our deploy process. It looks like current day we are testing migration from a fresh database and from "dirty" database. 

I need to do some testing with setting up a postgres database in our CICD pipeline and mess around with the liquibase action, but I believe that both of these steps are possible to contain in our pipeline (We can also add a changelog validation step to catch any issues as well).

The one thing I am unsure about is if we can fully automate this. I think that migrations can fail, but I don't know if this will fail the job, going to need to do some testing there. Worst case, we can still DO the migration testing automatically and the step will just be to "Check the job that there were no failures"

**Comment by epag** [comment]
Im going to estimate ~1.5-2 weeks to get this done, I will be doing all my testing in a fork so I can kick off a bunch of dummy releases and workflow runs without polluting the main repo

**Comment by james-d-brown** [comment]
The easiest way to do this is to:

1. Run an evaluation (e.g., system test scenario200) from a brand new database; and
2. Run an evaluation (e.g., system test scenario200) from a brand new database with the last software version and then repeat that exercise with the new software version.

Both evaluations should complete without exception. Completing without exception is really the only reliable indication of successful migration, although you can manually inspect the liquibase changelog for changes marked executed and marked ran and I often do that to be sure.

**Comment by james-d-brown** [comment]
In both cases, the software should be executed with the migrate flag on (`wres.attemptToMigrate=true`), which is the default in standalone mode (but not in cluster mode).

**Comment by epag** [comment]
Alright, I got the postgresql database hosted and was able to successfully connect to it via a helper script. When attempting to run a scenario with the connect to database enable it wasnt able to log in though. Will debug tomorrow

```
wres.pipeline.InternalWresException: Failed to log in the database.
	at wres.Functions.logExecution(Functions.java:961)
	at wres.Functions.evaluate(Functions.java:140)
	at wres.Functions.evaluate(Functions.java:97)
	at wres.helpers.MainUtilities.call(MainUtilities.java:107)
	at wres.Main.completeExecution(Main.java:206)
	at wres.Main.main(Main.java:126)
```

**Comment by james-d-brown** [comment]
You will need to create the relevant users on the db server with appropriate permissions (see the vlab wiki) and you will also need to create the tls assets because the app attempts a secure connection by default. With regard to that specific error above, that sounds a bit weak and/or buggy in our app code because the message is fairly meaningless and seemingly does not report a cause. That probably needs a separate ticket, though.

**Comment by epag** [comment]
> You will need to create the relevant users on the db server with appropriate permissions (see the vlab wiki) and you will also need to create the tls assets because the app attempts a secure connection by default. With regard to that specific error above, that sounds a bit weak and/or buggy in our app code because the message is fairly meaningless and seemingly does not report a cause. That probably needs a separate ticket, though.

Yup, created the wres_user, authorized the wres db and wres schema against them, Also I turned off SSL in the JAVA_OPT so it shouldn't be the security thing either.

Should be able to see the full logs here https://github.com/epag/wres-copy/actions/runs/9863767483/job/27237251392 

Ill continue on this tomorrow tho

**Comment by epag** [comment]
The workflow im working on as well https://github.com/epag/wres-copy/blob/master/.github/workflows/postgresql.yml

**Comment by james-d-brown** [comment]
OK, so the database is indeed null. Needs an improved error message, but that isn't the root cause.

There is an underlying bug here because the database should not be null in a situation where it is required because all db operations should be guarded by a check on whether a db is needed. Remember, the app runs in memory by default and only runs against a database when `wres.useDatabase=true`. Either way, the app has put itself into an incorrect state whereby a db operation is attempted against a null db, either because it failed to propagate an exception on creating the db or it failed to attempt db creation to begin with or perhaps there is an orchestration issue. Either way, that is a bug.

**Comment by epag** [comment]
Ok silly enough I just forgot to include a password override. Including one leads to a successful execution against the database. Full migration from fresh seems to work. Going to add in testing for migrating from previous latest after I fix the issue this uncovered

**Comment by epag** [comment]
Alright have it so I have it so we run the latest release against a fresh DB, it migrates and then we run the upcoming release. 

Then it clears the database and we migrate from scratch to the upcoming release.

I plan on this job running when changes to the `wres\wres-io\dist\lib\conf\database` path are made (Where the changelog file is) and also after a successful pre-release step

**Comment by epag** [comment]
Decided to have this job tied directly into the pre-release step. Finishing my testing today, and will update the wiki and then we can close this out
