### ISSUE TITLE
As a user, I want to see examples of how to use gzip compression to post files to the  COWRES in wikis and run scripts

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#337]
Should be a pretty low hanging fruit. I'll start with curl to identify the option to include at the command line, and then add it to the bash script and test it.  I'll then add the same option to the Python script and test it, as well. 

Let me start by experimenting using staging and looking at the logs,

Hank

**Comment by HankHerr-NOAA** [comment]
First, I just ran an old OHRFC evaluation posting a single file as input. The `curl` returns a "Content-Length" of 1904983. That's nearly identical to the size of the file locally (1904774) and remotely (the same). So its probably just adding a few bytes in transfer. From a web search, that's, "the size of the message body, in bytes, sent to the recipient." Okay.

So I looked up the `--compressed` flag for curl and found a description [here](https://everything.curl.dev/http/modify/compression.html):

> With this option enabled (and if the server supports it) it delivers the data in a compressed way and curl decompresses it before saving it or sending it to stdout.

From my end, however, `Content-Length` does not change: its still the size of the file sent before compression. I also see nothing indicating a compressed size in the tasker log. 

To see compression, I think I may need to look at the HAProxy logs. Let me log into the staging proxy machine, post some data via the proxy URL, and see if reflects the `--compression` flag,

Hank

**Comment by HankHerr-NOAA** [comment]
That's a no-go... I can't log into the staging proxy machine. Ugh. I might need to test using production.

Hank

**Comment by HankHerr-NOAA** [comment]
I posted ITSG-3675 for the staging issue. 

As for production, I can't see the logs, because there is no logging to see. The last log I can see is from the 276th day of the year, which is Oct 3, which corresponds to when we had issues with the proxy. Sigh.

Hank

**Comment by HankHerr-NOAA** [comment]
I posted ITSG-3677 to be able to view the Podman proxy container logs.  

At this point, I'm not sure how to actually confirm that data was compressed when it was sent over the wire the COWRES. I'll keep investigating a bit longer to see if there is another option,

Hank

**Comment by HankHerr-NOAA** [comment]
I can confirm that the `--compressed` option impacts data over the wire when I grab the output.  `curl` returns the number of bytes fetched to stdout and I compare that to the size of the file obtained and tell that there was compression and decompression happening. 

I still haven't figured out how to confirm the size of data over the wire POSTed to the COWRES.

Hank

**Comment by james-d-brown** [comment]
I think you need to say that you are POSTing a gzipped compressed body with `-H'Content-Encoding: gzip'` and ``"Content-Type: foo/bar"'` for whatever the unzipped content type is and then actually send a gzip-compressed body by gzipping it before sending.

**Comment by james-d-brown** [comment]
But perhaps `--compressed` does all of that magic for you, unsure. I thought that was top request that the server sends compressed content back, i.e., "I am a client that can handle compressed data if you want to send it".

**Comment by HankHerr-NOAA** [comment]
The documentation for `--compressed` is unclear on that.  The man page implies its just to receive data, but some online docs imply both. I should have trusted the man page.  I figured out that I could observed the data flowing through the stats page for the staging proxy; it appears in the "Bytes" for the "https-in" section. With or without `--compressed`, the size increases by the same amount: the size of the file uncompressed.

Okay, So `--compressed` is only for data received. 

I did do a `Content-Encoding` test earlier, but it failed to send. I probably left out the type. Let me figure out that way to do it. 

Note that, if the user is required to gzip the files before sending, then there is no reason to use the `-H` option: the data is already gzipped manually and WRES can parse gzipped data. 

Hank

**Comment by james-d-brown** [comment]
The `-H` option is saying "add this information to the header". This is so the server knows that the body is compressed (and what the original type is w/r to `Content-Type`), although that latter probably doesn't matter for our use case because we do type detection. I think what you mean is that the user doesn't need to manually gzip if it's already gzipped. Not sure about that. Remember, it's the body that needs to be gzipped. I don't think posting a gzipped file would work because it probably contains all sorts of other crap. I could be wrong.

**Comment by HankHerr-NOAA** [comment]
First, I need to figure out what `Content-Type` values are supported, because both "application/xml" and "text/xml" result in a 415 unsupported media type. I think you are saying I may not need that content type.  If I leave it out, I get a 500 server error.

What I'm hoping is that the user doesn't need to gzip it; that `curl` will handle that if its told to do so.  If `curl` will not do the gzipping itself and the user is required to handle any compression before posting, then the other header options aren't needed for the COWRES to handle the data.

As an example, for the OHRFC test case I'm using I normally post the data as a gzipped tarball. The `curl` command that works when posting the data is this:

`curl -v --cacert [appropriate cert] -F data=@2020MarchTest.tgz https://[COWRES]/job/[job]/input/right`

No `-H` options are needed. The data goes over the wire gzipped, is received by the tasker gzipped, and is placed on the file system gzipped, which is how the WRES reads it.  

So, if you documentation tells the user to gzip the data before sending, then it will just require a wiki change.  If we want our script to gzip the file before sending on the user's behalf, then we can code that into the script, but I don't think uncompressing it on the tasker end is needed. Just leave it gzipped.  

I hope I'm making sense, but I'm probably not. :)

Hank

**Comment by james-d-brown** [comment]
Right, that works because the WRES does content-type detection, but I am trying to explain the difference between content type and content encoding.

The reason you are getting that error is because the data posting method apparently only accepts multi-part form data. See `WresJobInput`.

**Comment by james-d-brown** [comment]
It may be easier to just ask users to post gzipped data as it will be quicker on the server side to process too. Sending a compressed stream will make it faster over the wire, but it adds a layer of compression and decompression, only for the server to then read the uncompressed data! So probably a situation where simplest is best and ask users to gzip their data before sending, which is probably most efficient and simplest all around.

**Comment by HankHerr-NOAA** [comment]
I think I just repeated your message, James. :)

Hank

**Comment by james-d-brown** [comment]
Yeah, I would just add that advice to the wiki and also notify Anna specifically. It is best for users too as they will see faster everything for a small cost of gzipping before sending.

**Comment by HankHerr-NOAA** [comment]
Actually, I don't think this is true:

> There are probably cases where a file can be gzipped, but it cannot be read while gzipped, so there would be value in telling the COWRES to gunzip the data before writing it to the file system. I would have to find those edge cases, however, to understand them. 

If a file cannot be read by the WRES, it has nothing to do with gzip; it has to do with the underlying file format.  So, gzipped or not, it won't be read. Hence, there shouldn't be any "edge cases" where data can't be handled gzipped, but can if gunzipped.  

Hank

**Comment by HankHerr-NOAA** [comment]
I'll make the wiki change and contact Anna.

Any value in having our scripts gzip files before sending them? I don't think so. It would just add language to the bash or Python scripts that are doing something the user should be responsible for, I think. Let me know if you disagree.

Thanks,

Hank

**Comment by james-d-brown** [comment]
> Actually, I don't think this is true:
> 
> > There are probably cases where a file can be gzipped, but it cannot be read while gzipped, so there would be value in telling the COWRES to gunzip the data before writing it to the file system. I would have to find those edge cases, however, to understand them.
> 
> If a file cannot be read by the WRES, it has nothing to do with gzip; it has to do with the underlying file format. So, gzipped or not, it won't be read. Hence, there shouldn't be any "edge cases" where data can't be handled gzipped, but can if gunzipped.
> 
> Hank

Right. There were those edge cases with an earlier/flawed implementation of the readers whereby reading and gzip handling were merged together without a good separation of concerns, but now the gzip handling is completely separate from content handling and can be put in front of any content type we support, so no edge cases.

**Comment by james-d-brown** [comment]
> I'll make the wiki change and contact Anna.
> 
> Any value in having our scripts gzip files before sending them? I don't think so. It would just add language to the bash or Python scripts that are doing something the user should be responsible for, I think. Let me know if you disagree.
> 
> Thanks,
> 
> Hank

Probably not because you could end up with files getting double-zipped, depending on what the user supplied. We can probably handle that too, server side - I think the unzipping is recursive - but it might not be and, in any case, no need for it. From memory, I think it is recursive but I believe there is also a ticket/bug related to massive recursively gzipped files whereby the inner files need to be fully unzipped in memory.

**Comment by HankHerr-NOAA** [comment]
I'm seeing large files being posted for SERFC, as well, that are not compressed. MNIG1 is an example `locationId`.  

Hank

**Comment by HankHerr-NOAA** [comment]
I'm not sure who to contact at SERFC; I can't remember the name. I'll do some searching for the right person to contact in a few minutes (I think its in my email history). 

The biggest files I'm seeing recently posted, however, are compressed ensembles from CNRFC. So Anna is compressing data, just only when the file is large. That's good.

Hank

**Comment by HankHerr-NOAA** [comment]
I think it was Ian Blaylock. I've emailed him to recommend he gzip the files, but the files were sort of small, so I don't know that he stands to gain much.  

With the wiki updated and emails sent, I think this ticket is done. Completing it. If anyone disagrees, just reopen it. 

Thanks,

Hank

**Comment by epag** [comment]
Dont believe this needs UAT
