### ISSUE TITLE
As a user, I want a pairs file with improved timing and variable information

### ISSUE THREAD

**Issue by james-d-brown** [NOAA-OWP/wres#37]
Given an evaluation that produces a pairs file
When I inspect the contents
Then I expect to see a variable name, a reference time and ISO8601 lead durations

**Comment by james-d-brown** [comment]
Encompasses vlab tickets #106053, #131433 and #99724. The reason for aggregating several minor changes is that the bulk of any effort in improving the pairs is to update the system test benchmarks.

These improvements are, in some sense, interim improvements because the pairs will, in some cases, contain a separate variable name for each side of the pairing and up to N reference times. However, those improvements will require large changes to the data model (specifically, the time-series metadata) and are beyond the scope of this ticket.

**Comment by james-d-brown** [comment]
Estimating 8 bananas because system test benchmarks are a PITA to update.

**Comment by james-d-brown** [comment]
Also replacing the "left" and "right" nomenclature with "observed" and "predicted".

**Comment by james-d-brown** [comment]
Sort order after adjustments (doesn't affect benchmark comparison, but useful for humans):

`(head -n 1 pairs.csv && tail -n +2 pairs.csv | sort -t, -k2d,2 -k1d,1 -k4,4 -k5,5 -k8n,8 -k9n,9 -k6,6 -k7,7 -k11,11 -k10n,10 ) > sorted_pairs.csv`

**Comment by HankHerr-NOAA** [comment]
You need to generate a new token with every push?  

I've been pushing to wres_output_service from GitHub using the ISED VSCode server without refreshing my token or entering a password for a couple of years now. Then again, I use the command line git to push. Maybe that's why?

Hank

**Comment by james-d-brown** [comment]
Not a new token, per se, because tokens are re-usable, but IDEA appears not to allow for recall of login or tokens, so it needs to be entered every time, and making a physical note of a token is not ideal.

**Comment by HankHerr-NOAA** [comment]
Got it. That is a pain.

Well, Eclipse allows for saving that information in a local file. I guess its time to switch to Eclipse. :)

Hank

**Comment by james-d-brown** [comment]
Pretty sure IDEA should save it too, but congratulations to legacy Eclipse for doing precisely one thing right :)

**Comment by james-d-brown** [comment]
I note that our UAT schedule has a mixture of open and closed tickets. Unsure whether tickets should be open or closed pending UAT, but we should probably choose one state and stick to it. Probably closed to remove from the backlog? But can a ticket be reopened if it fails UAT?

**Comment by james-d-brown** [comment]
To answer my own question, yes, a ticket can be reopened, so I propose we mark tickets pending UAT as closed. That way, we have a cleaner backlog. OK?

**Comment by HankHerr-NOAA** [comment]
As long as we are consistent about it, its fine with me. 

Hank

**Comment by james-d-brown** [comment]
Roger.

**Comment by james-d-brown** [comment]
Ay declaration that contains forecasts and a baseline should test it fully, perhaps system test scenario403, for example. I would run for 6.24 and RC1 and compare the sorted pairs for the main dataset and baseline and make sure you understand the differences. The sort command for the pairs was noted earlier:

`(head -n 1 pairs.csv && tail -n +2 pairs.csv | sort -t, -k2d,2 -k1d,1 -k4,4 -k5,5 -k8n,8 -k9n,9 -k6,6 -k7,7 -k11,11 -k10n,10 ) > sorted_pairs.csv`

Will need to adjust the file names for the baseline.

**Comment by ArvinEsmailzadeh-NOAA** [comment]
Posted Jobs:

Production: 2979885353446629838
Staging: 5541299738579576336

Compared the results I see the new row's, and naming convention and results look identical. I believe this passed UAT

Arvin
