### ISSUE TITLE
As a user, I want to calculate a difference between scores for a main and baseline scenario

### ISSUE THREAD

**Issue by james-d-brown** [NOAA-OWP/wres#47]
Given one or more score metrics calculated for a main and a baseline scenario
When I want to determine the difference between the scores for these two scenarios
Then I should be able to calculate this difference using WRES

( Difference in this context could mean various things, such as the straightforward difference or skill or some other comparator, but the scope of this ticket is a straightforward difference. )

**Comment by james-d-brown** [comment]
Tasks to complete, as currently envisaged:

- [ ] Adjust the declaration schema to allow for the declaration of score differences or metric residuals and implement validation / unit tests
- [ ] Adjust the canonical statistics format to clarify when a statistic is a residual or relative value (and the comparator used, as well as the two scenarios to which they refer) rather than an absolute value
- [ ] Allow for the calculation of residual statistics when declared
- [ ] Adjust the netcdf2, csv2 and png/svg statistics formats to clarify when a statistic is a residual or relative value (and the comparator used, as well as the two scenarios to which they refer) rather than an absolute value

**Comment by james-d-brown** [comment]
In terms of the schema, first thought is something like this for metrics that involve differences:

```
metrics:
  - sample size
  - pearson correlation coefficient
  - coefficient of determination
metrics_difference:
  - pearson correlation coefficient
  - coefficient of determination
```

Precise language, TBD, but the list composes metrics that represent a difference between the statistics that originate from an underlying metric for two modeling scenarios, `predicted` and `baseline`.

If we want other comparators in future (e.g., generic skill), we could add other lists/comparators, the goal being to maintain a relatively flat declaration structure, rather than something overly hierarchical, like `metrics_comparison` with the option of an explicit comparator for each list item.

**Comment by james-d-brown** [comment]
Second (and contrary) thought is that, from a user's perspective, the above isn't really the simplest possible declaration.

Why not simply append difference metrics to the list of metrics? Take any score metric and append the name "difference" to it and that should be declarable too. For example:

```
metrics:
  - sample size
  - pearson correlation coefficient
  - coefficient of determination
  - pearson correlation coefficient difference
  - coefficient of determination difference
```

No new top-level declaration option, but the same flexibility with combining ordinary and difference metrics. Also, there is no ambiguity about which metrics support differences because they will be formally enumerated along with all other metrics. No adjustment to the declaration schema, no adjustment to the canonical statistics format, so the first two task items disappear. Also, no potential overlap between two separate areas of declaration if we decide to include additional skill formulations in future (e.g., `brier skill score` in the default `metrics` context and `brier score` in a new `metrics_skill` context).

Under the hood, it may complicate things a little. It will require a new enumerated type for each new difference metric. In other words, you won't get a difference variant for free when adding a new metric. However, it should not require a new metric implementation for each new metric. Regardless, implementation details are less important than a clean api for users.

**Comment by james-d-brown** [comment]
Making good progress. Revised the tasks to complete in the first post. Progressing through the first task, but many of the subsequent tasks will have a similar structure (just a different set of scores).

**Comment by james-d-brown** [comment]
There is a question about whether metric differences should be included within the scope of metrics that are interpolated/chosen by the software when none are declared, but I lean towards omitting them from this list because it expands the set too much and they are, arguably, specialist metrics. With the new declaration language, this is simpler to justify because a user no longer explicitly declares "all valid" metrics (it would be confusing to argue that difference metrics are not valid), rather it is merely the set of metrics that the software chooses.

**Comment by james-d-brown** [comment]
Progress in https://github.com/NOAA-OWP/wres/tree/issue47

**Comment by james-d-brown** [comment]
Added support for numerically continuous single-valued datasets.

**Comment by james-d-brown** [comment]
Stepping a way from this for a few hours to do some additional backlog grooming in vlab.

**Comment by james-d-brown** [comment]
Largely completed this work. Last item remaining is top-level integration testing.

**Comment by james-d-brown** [comment]
Completed the top-level integration testing, will create a PR.

**Comment by james-d-brown** [comment]
Closed, pending UAT.

**Comment by HankHerr-NOAA** [comment]
James,

Just trying to understand the new process... Feature testing essentially comes in two forms for larger scale features such as this: (1) testing prior to deployment where we give a thumbs up that the feature is ready to go, and (2) UAT performed during a deployment where we make sure nothing broke since (1) was completed when using the revision to be deployed.

You put this ticket in a UAT state that matches that of other tickets to be tested during deployment. How should we make note that this ticket needs pre-deployment testing?  Or do you see nothing mechanically different between the two?

Anyway... I plan to test this starting either in my last couple of hours today or perhaps Tuesday of next week (depending on what else is on my plate). This appears to be just adding "difference" versions of metrics, as described in the comment,

https://github.com/NOAA-OWP/wres/issues/47#issuecomment-2243024215

It should be straight forward to create evaluations that include a baseline with statistics computed for it (can't recall the name of that option off the top of my head) and difference metrics, and examine the output for predicted and baseline to confirm the 
difference results.  I'll need to do that for simulations, single-valued forecasts, and ensemble forecasts and metrics. And I'll need to do that for any metric for which a "difference" version was created; presumably the YAML schema will give me that information.  Given this ticket is closed, I may create a separate task-issue next week for that testing.  

Thanks,

Hank

**Comment by james-d-brown** [comment]
I think this is all UAT. There are two stages insofar as merges are constantly occurring, which may break or conflict with committed but unreleased features, so there is always a need to check the actual RC in a deployment gate, but these are the two steps:

1. The substantive UAT, which can be completed at any time with a nominal/informal RC (one we have not formally nominated for a version);
2. The UAT gate in the deployment ticket where we repeat some tests to build confidence that (1) is not OBE using the actual RC.

All of this is a confidence building exercise, BTW.

**Comment by james-d-brown** [comment]
Will also need to ensure that wiki updates are included in the relevant deployment gate, notably to add the new metrics to the list.  It is worth noting that most, but not all, scores have a difference formulation. Skill scores do not because, even if they are calculated separately for a main and baseline dataset, the denominators differ as the baseline skill will be measured against a default baseline (e.g., climatology) for those skill scores that support it and a difference doesn't make sense in this context.

For your benefit, the new metrics are:

```
      - brier score difference
      - continuous ranked probability score difference
      - relative operating characteristic score difference
      - threat score difference
      - equitable threat score difference
      - frequency bias difference
      - probability of detection difference
      - probability of false detection difference
      - false alarm ratio difference
      - peirce skill score difference
      - bias fraction difference
      - coefficient of determination difference
      - pearson correlation coefficient difference
      - index of agreement difference
      - kling gupta efficiency difference
      - mean absolute error difference
      - mean error difference
      - mean square error difference
      - root mean square error difference
      - root mean square error normalized difference
      - sample size difference
      - sum of square error difference
      - volumetric efficiency difference
```

From a user's POV, it's as simple as adding the word "difference" to a named score when a baseline is present.

**Comment by james-d-brown** [comment]
As noted earlier, these are "specialist" metrics and are not part of the default set added by the software when no metrics are declared. This is partly to avoid breaking all the system tests, but mainly to avoid cluttering the "software decides" convenience with an absolute ton of metrics that users will not expect in most cases.

**Comment by james-d-brown** [comment]
Oh, and yes, I think the difference between our old approach and new approach is that we close tickets and move them to UAT, so if an issue arises at any moment from this point forwards, we create a new ticket to address that issue and that ticket may be subsequently added as a ticket to UAT (along with the original ticket), depending on the nature of the problem and the level of confidence we need.

**Comment by HankHerr-NOAA** [comment]
All sounds reasonable to me. When I start my testing, I'll create a "task" ticket of some sort to track and communicate the tests I perform and then spin off new tickets for issues I discover.  

When you can, please create a WRES GUI ticket for Arvin to add the stats to those available in the GUI. Or perhaps that can wait until we are closer to deployment. 

Thanks,

Hank

**Comment by HankHerr-NOAA** [comment]
I'm going to block time Tuesday morning to begin this testing. Unfortunately, the three hour meeting is going to pick back up in a bit and reach 4 hours before its done. Yay!

More on Tuesday,

Hank

**Comment by ArvinEsmailzadeh-NOAA** [comment]
Is there a specific way we want to UAT this ticket? Is there a decleration? I believe this ticket was tested with my other tests for #62 

Arvin

**Comment by james-d-brown** [comment]
Yeah, Hank created #62 to test #47, so done.
