### ISSUE TITLE
As a developer, I want to a system test scenario executed in memory

### ISSUE THREAD

**Issue by james-d-brown** [NOAA-OWP/wres#59]
Given a github release, which external users will typically deploy "in memory"
When I want to build confidence in our releases for external users
Then there should be a system test sequence that executes in memory, alongside the other scenarios

**Comment by james-d-brown** [comment]
Currently, we have three cycles, one for external writers, one for H2 and one for the legacy evaluation language. We need one cycle in memory to catch issues with this execution pathway before we release.

**Comment by epag** [comment]
This should be easy enough to add into the workflow

**Comment by epag** [comment]
https://github.com/NOAA-OWP/wres/pull/60

Created a PR to add this

**Comment by james-d-brown** [comment]
Sounds good, thanks. FWIW, I would not run this with external writers, as there is a separate test cycle for that.

**Comment by epag** [comment]
> Sounds good, thanks. FWIW, I would not run this with external writers, as there is a separate test cycle for that.

Didnt push yet so ill remove that quick and then submit the changes
