### ISSUE TITLE
As a developer, I want to be able to resolve all dependencies for WRES

### ISSUE THREAD

**Issue by ArvinEsmailzadeh-NOAA** [NOAA-OWP/wres#63]
When going to work on the new deployment steps for WRES and github, I cloned a fresh instance of the project. This led to dependencies needing to be pulled in and downloaded which led immediately to this: 

![image](https://github.com/user-attachments/assets/89efe8de-e6a8-450f-b2a0-7275633f5287)

 Doing some initial research I noticed this: https://plugins.gradle.org/plugin/org.kordamp.gradle.markdown

"This plugin version will no longer resolve after JCenter becomes a permanent redirect to Maven Central as it uses dependencies only found in JCenter."

From my understanding the transitive dependency called "com.overzealous:remark:1.1.0" used in "org.kordamp" only exists in JCenter which is now deprecated. Which is what the blog post above is saying. The plugin "com.overzealous:remark:1.1.0" is only found in JCenter and because of that the "org.kordamp" cannot resolve.

**Comment by epag** [comment]
James do you know if we are still using this plugin?

I see this TODO in the build.gradle that would seem to imply that we still need to implement the use of this plugin, but it could just be a TODO that was never removed. I don't see any obvious usages of it through the codebase though

https://github.com/NOAA-OWP/wres/blob/b1a52a736a678d7ceae022eeab886391e1c16c43/build.gradle#L1728-L1734

**Comment by epag** [comment]
Nevermind, it appears to be used here for protobuff stuff it appears 

https://github.com/NOAA-OWP/wres/blob/b1a52a736a678d7ceae022eeab886391e1c16c43/build.gradle#L747-L761

**Comment by james-d-brown** [comment]
Fixed this in branch issue36 using this helpful post (scroll down):

https://github.com/kordamp/markdown-gradle-plugin/issues/36

Won't be merging that branch for a while, but if someone wants to fix and merge, this is the fix (add to existing `buildscript` configuration):

```
buildscript {

    // Workaround for missing transitive dependency for plugin org.kordamp.gradle.markdown
    // https://github.com/kordamp/markdown-gradle-plugin/issues/36
    configurations.all {
        resolutionStrategy.dependencySubstitution {
            substitute module("com.overzealous:remark:1.1.0") using module("com.wavefront:remark:2023-07.07") because "not available on maven central anymore"
        }
    }
}
```

**Comment by epag** [comment]
> Fixed this in branch issue36 using this helpful post (scroll down):
> 
> [kordamp/markdown-gradle-plugin#36](https://github.com/kordamp/markdown-gradle-plugin/issues/36)
> 
> Won't be merging that branch for a while, but if someone wants to fix and merge, this is the fix (add to existing `buildscript` configuration):
> 
> ```
> buildscript {
> 
>     // Workaround for missing transitive dependency for plugin org.kordamp.gradle.markdown
>     // https://github.com/kordamp/markdown-gradle-plugin/issues/36
>     configurations.all {
>         resolutionStrategy.dependencySubstitution {
>             substitute module("com.overzealous:remark:1.1.0") using module("com.wavefront:remark:2023-07.07") because "not available on maven central anymore"
>         }
>     }
> }
> ```

Im waiting for ITSG to respond on the cert question I posted so ill go ahead and add this quick. Thanks for finding the solution

**Comment by epag** [comment]
Created a PR with these changes. Once they are submitted you can continue with the deployment process Arvin

**Comment by epag** [comment]
Changes merged in, you should be able to continue with deploy
